### ISSUE TITLE
Make repo private for PoN data

### ISSUE THREAD

**Issue by hassanfa** [Clinical-Genomics/reference-files#35]
Is it possible to make this repo private so I can add PoN* data here?

I'd like to also be added as admin so I can do push/release as well, please.

*PoN: pool|panel of normals

**Comment by dnil** [comment]
In that case we would need one more repo that is public for the other files to keep our MIP setup public, so rather create a new one! Check with @jemten and @henrikstranneheim how they handle their static db snapshot/dump files between versions?

I suppose there is a very limited number of positions on the panels, but in general we will anyway need larger dbs for exomes and genomes..

**Comment by hassanfa** [comment]
They are flat files (tsv, csv, etc), VCFs, or co-realigned bam/sam/cram files. Accompanied by case and sample IDs used to generate them. I am not so keen on dbs and db dumps. Flat files are easier to deal with.

I thought it'd be smart to keep all our reference files in a single repo, but if taking this repo private kills its purpose then this issue is irrelevant. I'll dump them in another repo.

**Comment by jemten** [comment]
The point with this repo was to store and version control small reference files and configs that are public. I think that it is better to have a separate repo for non-public files.

**Comment by hassanfa** [comment]
I'll close this for now. I'll look into encryption solutions to encrypt data and add a key somewhere in another private repo. Until then: so long till I open this again 😄

**Comment by henrikstranneheim** [comment]
> I'd like to also be added as admin so I can do push/release as well, please.

Done
